name: attendance_manager_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # API & Google Sheets
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0

  # Date & Time Handling
  intl: ^0.18.1
  go_router: ^14.8.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.1 
  json_annotation: ^4.8.1   
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.1      
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/.env

